apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: rke2
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: RKE2ControlPlaneTemplate
      name: rke2-control-plane
    machineInfrastructure:
      ref:
        kind: ElementalMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: rke2-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: ElementalClusterTemplate
      name: rke2-cluster
  workers:
    machineDeployments:
      - class: rke2-default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: RKE2ConfigTemplate
              name: rke2-default-worker-bootstrap
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: ElementalMachineTemplate
              name: rke2-default-worker
  variables:
    - name: controlPlaneEndpointHost
      required: true
      schema:
        openAPIV3Schema:
          type: string
    - name: controlPlaneEndpointPort
      required: true
      schema:
        openAPIV3Schema:
          type: integer
          default: 6443
    - name: vipInterface
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: "eth0"
    - name: k8sVersion
      required: true
      schema:
        openAPIV3Schema:
          type: string
  patches:
    - name: elementalClusterTemplate
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: ElementalClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: add
              path: "/spec/template/spec/controlPlaneEndpoint/host"
              valueFrom:
                variable: controlPlaneEndpointHost
            - op: add
              path: "/spec/template/spec/controlPlaneEndpoint/port"
              valueFrom:
                variable: controlPlaneEndpointPort
    - name: rKE2ControlPlaneTemplate
      definitions:
        - selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: RKE2ControlPlaneTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: add
              path: "/spec/template/spec/version"
              valueFrom:
                variable: k8sVersion
            - op: add
              path: "/spec/template/spec/files"
              valueFrom:
                template: |
                  - content: |
                      apiVersion: v1
                      kind: Pod
                      metadata:
                        creationTimestamp: null
                        name: kube-vip
                        namespace: kube-system
                      spec:
                        containers:
                        - args:
                          - manager
                          env:
                          - name: vip_arp
                            value: "true"
                          - name: port
                            value: {{ .controlPlaneEndpointPort }}
                          - name: vip_nodename
                            valueFrom:
                              fieldRef:
                                fieldPath: spec.nodeName
                          - name: vip_interface
                            value: {{ .vipInterface }}
                          - name: vip_cidr
                            value: "32"
                          - name: dns_mode
                            value: first
                          - name: cp_enable
                            value: "true"
                          - name: cp_namespace
                            value: kube-system
                          - name: svc_enable
                            value: "true"
                          - name: svc_leasename
                            value: plndr-svcs-lock
                          - name: vip_leaderelection
                            value: "true"
                          - name: vip_leasename
                            value: plndr-cp-lock
                          - name: vip_leaseduration
                            value: "5"
                          - name: vip_renewdeadline
                            value: "3"
                          - name: vip_retryperiod
                            value: "1"
                          - name: address
                            value: {{ .controlPlaneEndpointHost }}
                          - name: prometheus_server
                            value: :2112
                          image: ghcr.io/kube-vip/kube-vip:v0.8.0
                          imagePullPolicy: IfNotPresent
                          name: kube-vip
                          resources: {}
                          securityContext:
                            capabilities:
                              add:
                              - NET_ADMIN
                              - NET_RAW
                          volumeMounts:
                          - mountPath: /etc/kubernetes/admin.conf
                            name: kubeconfig
                        hostAliases:
                        - hostnames:
                          - kubernetes
                          ip: 127.0.0.1
                        hostNetwork: true
                        volumes:
                        - hostPath:
                            path: /etc/rancher/rke2/rke2.yaml
                          name: kubeconfig
                      status: {}
                    owner: root:root
                    path: /var/lib/rancher/rke2/server/manifests/kube-vip.yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElementalClusterTemplate
metadata:
  name: rke2-cluster
spec:
  template:
    spec:
      controlPlaneEndpoint: 
        host: ""
        port: 6443
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlaneTemplate
metadata:
  name: rke2-control-plane
spec:
  template:
    spec:
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ElementalMachineTemplate
        name: rke2-control-plane
      serverConfig:
        disableComponents:
          kubernetesComponents:
            - cloudController
      nodeDrainTimeout: 2m
      registrationMethod: "control-plane-endpoint"
      rolloutStrategy:
        type: "RollingUpdate"
        rollingUpdate:
          maxSurge: 1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElementalMachineTemplate
metadata:
  name: rke2-control-plane
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: rke2-default-worker-bootstrap
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElementalMachineTemplate
metadata:
  name: rke2-default-worker
spec:
  template:
    spec: {}
