---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - elementalclusters
  - elementalclustertemplates
  - elementalhosts
  - elementalmachines
  - elementalmachinetemplates
  - elementalregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - elementalclusters/finalizers
  - elementalclustertemplates/finalizers
  - elementalhosts/finalizers
  - elementalmachines/finalizers
  - elementalmachinetemplates/finalizers
  - elementalregistrations/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - elementalclusters/status
  - elementalclustertemplates/status
  - elementalhosts/status
  - elementalmachines/status
  - elementalmachinetemplates/status
  - elementalregistrations/status
  verbs:
  - get
  - patch
  - update
