name: "Default user"
stages:
  initramfs:
  - if: |
          cat /proc/cmdline | grep -q "CDLABEL"
    name: "Setup user for live CD"
    files:
    - path: /etc/issue.d/99_passwd
      content: |
        Login with username=root, password=r0s@pwd1
    ensure_entities:
    - path: /etc/shadow
      entity: |
        kind: "shadow"
        username: "root"
        password: "r0s@pwd1"
